CREATE CONSTRAINT asset_code IF NOT EXISTS FOR (n:Asset) REQUIRE n.code IS UNIQUE;
CREATE CONSTRAINT component_code IF NOT EXISTS FOR (n:Component) REQUIRE n.code IS UNIQUE;
CREATE CONSTRAINT rule_code IF NOT EXISTS FOR (n:Rule) REQUIRE n.code IS UNIQUE;
CREATE CONSTRAINT manual_code IF NOT EXISTS FOR (n:Manual) REQUIRE n.code IS UNIQUE;
CREATE CONSTRAINT spare_part_code IF NOT EXISTS FOR (n:SparePart) REQUIRE n.code IS UNIQUE;
CREATE CONSTRAINT inventory_code IF NOT EXISTS FOR (n:InventoryItem) REQUIRE n.code IS UNIQUE;
CREATE CONSTRAINT purchase_request_id IF NOT EXISTS FOR (n:PurchaseRequest) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT user_id IF NOT EXISTS FOR (n:User) REQUIRE n.id IS UNIQUE;

